### ISSUE TITLE
Toggle for fake geolocation in staging environment

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#15]
To allow using a location near the facilities but also test that geolocation is working, figure out a way to toggle the faking of user geolocation. A url parameter should do the trick.

Also, take into account that (at least in Chrome) geolocation is not allowed for non-HTTPs sites. We may need to enable HTTPs for stg.

**Comment by bcardiff** [comment]
`http(s)://host/?user_position=real` will disable the fake location from the settings file for testing in the current location. Due to elm routing module the query string is removed, but the param is effectively set (until the next full page reload).

There is a deployment issue for stg environment and https though. 
For development ngrok can be used to build a https tunnel.
Settings.yml (overridable with ENV vars) is used to setup de initial position and fake user location.

cc: @vtiffenberg @juanedi
