### ISSUE TITLE
Change encoding for the downloaded csv at "Download full dataset"

### ISSUE THREAD

**Issue by manumoreira** [instedd/facility-public-portal#169]
In the current portals that have French or Portuguese versions, the downloaded CSV at 'Download full dataset' (api/dump) has issues with accents based on the encoding, using UTF-8 with BOM seems to fix the issue.

**Comment by manumoreira** [comment]
This is just an issue of Excel not recognizing the UTF-8 encoding by default

**Comment by lmatayoshi** [comment]
Just providing more details here.

As @manumoreira said, the problem isn't the downloaded file: Every string in that file is encoded in `UTF-8` format. Moreover, the file itself is encoded in `UTF-8`. In MacOs, you can check that by using the command: `file -I` on the downloaded file.

The problem is in the way Excel attempts to read the `.csv`. Fore some reason, it won't use `UTF-8` as the default option. A way to fix this, so datasets aren't displayed with broken characters in Excel, is to import the `.csv` file specifying the encoding. To do that, go to: `Data -> From Text -> Import`, and then choose `65001: Unicode (UTF-8)` from the drop-down list that appears next to `File origin`.

The `UTF-8` with `BOM` doesn't seem quite correct because:
[According to the Unicode standard, the BOM for UTF-8 files is not recommended](https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom/2223926#2223926)
